SELECT * FROM AIRBNB_BKK.DBT_AWASADASATH_AGGREGATE.AGG_DAILY_NEIGHBORHOOD_PERFORMANCE ;
DESC TABLE AIRBNB_BKK.DBT_AWASADASATH_AGGREGATE.AGG_DAILY_NEIGHBORHOOD_PERFORMANCE;

SELECT * FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS ;
DESC TABLE AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS;

SELECT * FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.FCT_REVIEWS ;
DESC TABLE AIRBNB_BKK.DBT_AWASADASATH_CORE.FCT_REVIEWS;

SELECT * FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.FCT_DAILY_ACTIVITY ;
DESC TABLE AIRBNB_BKK.DBT_AWASADASATH_CORE.FCT_DAILY_ACTIVITY;

SELECT TABLE_NAME, ROW_COUNT, BYTES 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA IN ('RAW', 'CORE', 'MART')
ORDER BY ROW_COUNT DESC;
