-- Clustering Segmentation Map
SELECT 
    PCA_X,
    PCA_Y,
    CLUSTER_LABEL
FROM AIRBNB_BKK.DBT_AWASADASATH.CLUSTER_LISTINGS
LIMIT 10000;

--Anomalies Detection
SELECT 
    T1.LISTING_ID,
    T2.NEIGHBOURHOOD_NAME,
    T2.PRICE as "Asking Price",
    ROUND(AVG(T2.PRICE) OVER (PARTITION BY T2.NEIGHBOURHOOD_NAME), 0) as "Area Avg Price",
    (T2.PRICE - ROUND(AVG(T2.PRICE) OVER (PARTITION BY T2.NEIGHBOURHOOD_NAME), 0)) as "Diff from Area"
FROM AIRBNB_BKK.DBT_AWASADASATH.DETECT_ANOMALIES T1
JOIN AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS T2 
    ON T1.LISTING_ID = T2.LISTING_ID
WHERE T1.IS_ANOMALY = -1 
ORDER BY 5 DESC
LIMIT 10;

-- Prediction Accuracy Check
SELECT 
    ROW_NUMBER() OVER (ORDER BY RANDOM()) as "Item_No",
    PRICE as "Actual Price",
    PREDICTED_PRICE as "AI Predicted Price"
FROM AIRBNB_BKK.DBT_AWASADASATH.PREDICT_PRICE
WHERE PRICE BETWEEN 1000 AND 5000 AND PREDICTED_PRICE < 50000
LIMIT 80;

-- Sentiment Analysis
SELECT 
    REVIEW_TEXT, 
    SENTIMENT_SCORE
FROM AIRBNB_BKK.DBT_AWASADASATH.MART_SENTIMENT;
