-- Total Listings
SELECT 
    COUNT(*) as "Total Listings"
FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS;

-- Avg Price
SELECT 
    ROUND(AVG(PRICE),0) as "Avg Price (฿)"
FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS;

-- Total Neighborhoods
SELECT 
    COUNT(DISTINCT NEIGHBOURHOOD_NAME) as "Total Neighborhoods"
FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS;

-- Most Expensive Neighborhoods
SELECT 
    NEIGHBOURHOOD_NAME,
    COUNT(*) as Total_Listings,
    ROUND(AVG(PRICE), 2) as Avg_Price
FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS
GROUP BY 1
HAVING COUNT(*) > 10
ORDER BY 3 DESC
LIMIT 10;

-- Top 10 Popular Neighborhoods
SELECT NEIGHBOURHOOD_NAME, COUNT(*) as Total_Listings
FROM AIRBNB_BKK.DBT_AWASADASATH_CORE.DIM_LISTINGS
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;
