USE ROLE ACCOUNTADMIN;

-- สร้าง Schema สำหรับเก็บ Policy
CREATE SCHEMA IF NOT EXISTS AIRBNB_BKK.DBT_AWASADASATH;

-- 3. Masking Policy
CREATE OR REPLACE MASKING POLICY AIRBNB_BKK.DBT_AWASADASATH.HOST_MASK AS (val string) returns string ->
  CASE
    WHEN current_role() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE '***MASKED***'
  END;


GRANT APPLY ON MASKING POLICY AIRBNB_BKK.DBT_AWASADASATH.HOST_MASK TO ROLE ACCOUNTADMIN;
GRANT APPLY ON MASKING POLICY AIRBNB_BKK.DBT_AWASADASATH.HOST_MASK TO ROLE SYSADMIN;

-- ลอง Select ดูข้อมูล
SELECT listing_id, host_name 
FROM dim_listings 
LIMIT 10;

-- ช่อง host_name ต้องเป็นชื่อคนปกติถ้าเป็น ACCOUNT ADMIN
